Cleanup go version
This project doesn't seems to work on go 1.12, because of the usage of
`NewRequestWithContext`, I've tooked the liberty to bump it to 1.15 and
added a `.go-version` file.

```
winterfell~/zat(main|✔) % go build
./main.go:382:15: undefined: http.NewRequestWithContext
```